fix

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -1,4 +1,4 @@
-name: Tabib-PushFlow
+name: Laravel CI
 
 on:
   push:
@@ -7,8 +7,33 @@ on:
     branches: ["main"]
 
 jobs:
-  Tabib-PushFlow:
+  setup:
     runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: shivammathur/setup-php@v2
+        with:
+          php-version: "8.3"
+          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
+          coverage: none
+
+      - name: Install Dependencies
+        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+
+      - name: Copy .env
+        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
+
+      - name: Generate key
+        run: php artisan key:generate
+
+      - name: Directory Permissions
+        run: chmod -R 777 storage bootstrap/cache
+
+  migrations:
+    runs-on: ubuntu-latest
+    needs: setup
 
     services:
       mysql:
@@ -33,18 +58,6 @@ jobs:
           extensions: mbstring, pdo, pdo_mysql, xml, intl, json
           coverage: none
 
-      - name: Install Dependencies
-        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
-
-      - name: Copy .env
-        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
-
-      - name: Generate key
-        run: php artisan key:generate
-
-      - name: Directory Permissions
-        run: chmod -R 777 storage bootstrap/cache
-
       - name: Run migrations
         env:
           DB_CONNECTION: mysql
@@ -53,8 +66,25 @@ jobs:
           DB_DATABASE: test_db
           DB_USERNAME: root
           DB_PASSWORD: password
-        run: php artisan migrate --force
-        continue-on-error: true # Continue even if migrations fail
+        run: |
+          php artisan migrate --force
+          if [ $? -ne 0 ]; then
+            echo "There was an error during migrations"
+            echo "migrations_failed=true" >> $GITHUB_ENV
+          fi
+
+  tests:
+    runs-on: ubuntu-latest
+    needs: migrations
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: shivammathur/setup-php@v2
+        with:
+          php-version: "8.3"
+          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
+          coverage: none
 
       - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
         env:
@@ -64,17 +94,82 @@ jobs:
           DB_DATABASE: test_db
           DB_USERNAME: root
           DB_PASSWORD: password
-        run: php artisan test
-        continue-on-error: true # Continue even if tests fail
+        run: |
+          php artisan test
+          if [ $? -ne 0 ]; then
+            echo "There was an error during tests"
+            echo "tests_failed=true" >> $GITHUB_ENV
+          fi
+
+  code_style:
+    runs-on: ubuntu-latest
+    needs: setup
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: shivammathur/setup-php@v2
+        with:
+          php-version: "8.3"
+          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
+          coverage: none
 
       - name: Run Pint (Code Style)
-        run: vendor/bin/pint --test
-        continue-on-error: true # Continue even if Pint fails
+        run: |
+          vendor/bin/pint --test
+          if [ $? -ne 0 ]; then
+            echo "There was an error during Pint"
+            echo "pint_failed=true" >> $GITHUB_ENV
+          fi
+
+  static_analysis:
+    runs-on: ubuntu-latest
+    needs: setup
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: shivammathur/setup-php@v2
+        with:
+          php-version: "8.3"
+          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
+          coverage: none
 
       - name: Run PHPStan (Static Analysis)
-        run: vendor/bin/phpstan analyse
-        continue-on-error: true # Continue even if PHPStan fails
+        run: |
+          vendor/bin/phpstan analyse
+          if [ $? -ne 0 ]; then
+            echo "There was an error during PHPStan"
+            echo "phpstan_failed=true" >> $GITHUB_ENV
+          fi
+
+  refactoring:
+    runs-on: ubuntu-latest
+    needs: setup
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: shivammathur/setup-php@v2
+        with:
+          php-version: "8.3"
+          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
+          coverage: none
 
       - name: Run Rector (Automated Refactoring)
-        run: vendor/bin/rector process --dry-run
-        continue-on-error: true # Continue even if Rector fails
+        run: |
+          vendor/bin/rector process --dry-run
+          if [ $? -ne 0 ]; then
+            echo "There was an error during Rector"
+            echo "rector_failed=true" >> $GITHUB_ENV
+          fi
+
+  fail_job_if_any_step_failed:
+    runs-on: ubuntu-latest
+    needs: [migrations, tests, code_style, static_analysis, refactoring]
+
+    steps:
+      - name: Fail job if any step failed
+        if: env(migrations_failed) == 'true' || env(tests_failed) == 'true' || env(pint_failed) == 'true' || env(phpstan_failed) == 'true' || env(rector_failed) == 'true'
+        run: exit 1
+        shell: bash
